version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USERNAME}']
      interval: 10s
      timeout: 3s
      retries: 5
  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: 
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable",
        "up",
      ]
    restart: on-failure
  server:
    build: .
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_SOURCE: postgresql
      DB_TYPE: ${DB_TYPE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_TEST: ${DB_TEST_NAME}
      DB_HOST: db
      DB_PORT: 5432
      DB_SSL_MODE: disable
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8888:8888'

volumes:
  postgres_data:
