// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID                     int32            `json:"id"`
	ServiceID              int32            `json:"service_id"`
	UserID                 int32            `json:"user_id"`
	CollaborationStartDate pgtype.Timestamp `json:"collaboration_start_date"`
	ContractValue          float64          `json:"contract_value"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
}

type Product struct {
	ID          int32            `json:"id"`
	Price       float64          `json:"price"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Password  string           `json:"password"`
	Email     pgtype.Text      `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
